In [1]:
import pandas as pd
from assets import models

from assets.database import db_session

In [2]:
df = pd.read_csv("./data.csv")

In [3]:
df.head()

        date  subscribers  reviews
0  2019/1/17         2671      194
1  2019/1/18         2671      195
2  2019/1/19         2674      197
3  2019/1/20         2685      199
4  2019/1/21         2695      199

In [4]:
df.iloc[0,0]

'2019/1/17'

In [5]:
import datetime

In [6]:
date = datetime.datetime.strptime(df.iloc[0,0], '%Y/%m/%d').date()
date

datetime.date(2019, 1, 17)

In [7]:
def read_data():
    from assets import models
    df = pd.read_csv("./data.csv")
    for index , _df in df.iterrows():
        #date型に変更
        date = datetime.datetime.strptime(_df['date'],'%Y/%m/%d').date()

        row = models.Data(date=date,subscribers=_df['subscribers'] , reviews=_df["reviews"])
        db_session.add(row)

    db_session.commit()

2020-08-26 06:45:22,085 INFO sqlalchemy.engine.base.Engine SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2020-08-26 06:45:22,093 INFO sqlalchemy.engine.base.Engine ()
2020-08-26 06:45:22,093 INFO sqlalchemy.engine.base.Engine SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2020-08-26 06:45:22,093 INFO sqlalchemy.engine.base.Engine ()
2020-08-26 06:45:22,097 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2020-08-26 06:45:22,109 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,113 INFO sqlalchemy.engine.base.Engine ('2019-01-17', 2671, 194, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,131 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,135 INFO sqlalchemy.engine.base.Engine ('2019-01-18', 2671, 195, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,139 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,143 INFO sqlalchemy.engine.base.Engine ('2019-01-19', 2674, 197, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,147 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,147 INFO sqlalchemy.engine.base.Engine ('2019-01-20', 2685, 199, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,151 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,155 INFO sqlalchemy.engine.base.Engine ('2019-01-21', 2695, 199, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,159 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,163 INFO sqlalchemy.engine.base.Engine ('2019-01-22', 2701, 200, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,167 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,167 INFO sqlalchemy.engine.base.Engine ('2019-01-23', 2710, 200, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,171 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,175 INFO sqlalchemy.engine.base.Engine ('2019-01-24', 2718, 201, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,179 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,179 INFO sqlalchemy.engine.base.Engine ('2019-01-25', 2722, 201, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,183 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,187 INFO sqlalchemy.engine.base.Engine ('2019-01-26', 2725, 201, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,191 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,191 INFO sqlalchemy.engine.base.Engine ('2019-01-27', 2734, 202, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,195 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,199 INFO sqlalchemy.engine.base.Engine ('2019-01-28', 2753, 204, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,199 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,203 INFO sqlalchemy.engine.base.Engine ('2019-01-29', 2773, 206, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,207 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,207 INFO sqlalchemy.engine.base.Engine ('2019-01-30', 2785, 208, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,211 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,215 INFO sqlalchemy.engine.base.Engine ('2019-01-31', 2803, 210, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,215 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,219 INFO sqlalchemy.engine.base.Engine ('2019-02-01', 2845, 211, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,219 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,219 INFO sqlalchemy.engine.base.Engine ('2019-02-02', 2847, 213, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,223 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,223 INFO sqlalchemy.engine.base.Engine ('2019-02-03', 2847, 213, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,227 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,231 INFO sqlalchemy.engine.base.Engine ('2019-02-04', 2851, 217, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,232 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,236 INFO sqlalchemy.engine.base.Engine ('2019-02-05', 2852, 218, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,240 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,240 INFO sqlalchemy.engine.base.Engine ('2019-02-06', 2857, 219, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,244 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,244 INFO sqlalchemy.engine.base.Engine ('2019-02-07', 2861, 220, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,248 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,248 INFO sqlalchemy.engine.base.Engine ('2019-02-08', 2865, 222, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,252 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,252 INFO sqlalchemy.engine.base.Engine ('2019-02-09', 2870, 224, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,252 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,256 INFO sqlalchemy.engine.base.Engine ('2019-02-10', 2875, 224, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,260 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,264 INFO sqlalchemy.engine.base.Engine ('2019-02-11', 2892, 227, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,264 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,268 INFO sqlalchemy.engine.base.Engine ('2019-02-12', 2906, 229, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,272 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,272 INFO sqlalchemy.engine.base.Engine ('2019-02-13', 2919, 229, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,272 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,276 INFO sqlalchemy.engine.base.Engine ('2019-02-14', 2942, 231, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,276 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,280 INFO sqlalchemy.engine.base.Engine ('2019-02-15', 2974, 232, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,280 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,285 INFO sqlalchemy.engine.base.Engine ('2019-02-16', 2977, 234, '2020-08-26 06:45:17.772911')

2020-08-26 06:45:22,285 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,288 INFO sqlalchemy.engine.base.Engine ('2019-02-17', 2978, 234, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,292 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,292 INFO sqlalchemy.engine.base.Engine ('2019-02-18', 2981, 234, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,296 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,301 INFO sqlalchemy.engine.base.Engine ('2019-02-19', 2983, 234, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,301 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,301 INFO sqlalchemy.engine.base.Engine ('2019-02-20', 2984, 237, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,305 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,305 INFO sqlalchemy.engine.base.Engine ('2019-02-21', 2987, 239, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,308 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,308 INFO sqlalchemy.engine.base.Engine ('2019-02-22', 2989, 239, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,313 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,313 INFO sqlalchemy.engine.base.Engine ('2019-02-23', 2993, 241, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,317 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,317 INFO sqlalchemy.engine.base.Engine ('2019-02-24', 2995, 241, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,321 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,321 INFO sqlalchemy.engine.base.Engine ('2019-02-25', 3009, 241, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,325 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,329 INFO sqlalchemy.engine.base.Engine ('2019-02-26', 3014, 243, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,329 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,333 INFO sqlalchemy.engine.base.Engine ('2019-02-27', 3023, 243, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,337 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,337 INFO sqlalchemy.engine.base.Engine ('2019-02-28', 3031, 243, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,337 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,341 INFO sqlalchemy.engine.base.Engine ('2019-03-01', 3052, 244, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,341 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,345 INFO sqlalchemy.engine.base.Engine ('2019-03-02', 3060, 245, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,345 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,349 INFO sqlalchemy.engine.base.Engine ('2019-03-03', 3062, 246, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,349 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,353 INFO sqlalchemy.engine.base.Engine ('2019-03-04', 3063, 249, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,353 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,357 INFO sqlalchemy.engine.base.Engine ('2019-03-05', 3066, 252, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,357 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,361 INFO sqlalchemy.engine.base.Engine ('2019-03-06', 3071, 254, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,365 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,365 INFO sqlalchemy.engine.base.Engine ('2019-03-07', 3074, 255, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,369 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,369 INFO sqlalchemy.engine.base.Engine ('2019-03-08', 3076, 256, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,369 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,373 INFO sqlalchemy.engine.base.Engine ('2019-03-09', 3077, 258, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,373 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,373 INFO sqlalchemy.engine.base.Engine ('2019-03-10', 3080, 258, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,373 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,377 INFO sqlalchemy.engine.base.Engine ('2019-03-11', 3087, 261, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,377 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,377 INFO sqlalchemy.engine.base.Engine ('2019-03-12', 3089, 261, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,381 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,381 INFO sqlalchemy.engine.base.Engine ('2019-03-13', 3093, 262, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,385 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,385 INFO sqlalchemy.engine.base.Engine ('2019-03-14', 3098, 262, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,389 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,393 INFO sqlalchemy.engine.base.Engine ('2019-03-15', 3104, 262, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,393 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,397 INFO sqlalchemy.engine.base.Engine ('2019-03-16', 3112, 262, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,401 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,401 INFO sqlalchemy.engine.base.Engine ('2019-03-17', 3120, 262, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,405 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,405 INFO sqlalchemy.engine.base.Engine ('2019-03-18', 3131, 265, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,405 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,409 INFO sqlalchemy.engine.base.Engine ('2019-03-19', 3142, 266, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,409 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,413 INFO sqlalchemy.engine.base.Engine ('2019-03-20', 3162, 266, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,413 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,417 INFO sqlalchemy.engine.base.Engine ('2019-03-21', 3173, 268, '2020-08-26 06:45:17.772911')

2020-08-26 06:45:22,417 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,421 INFO sqlalchemy.engine.base.Engine ('2019-03-22', 3180, 269, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,421 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,425 INFO sqlalchemy.engine.base.Engine ('2019-03-23', 3187, 271, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,425 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,425 INFO sqlalchemy.engine.base.Engine ('2019-03-24', 3189, 271, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,429 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,433 INFO sqlalchemy.engine.base.Engine ('2019-03-25', 3196, 274, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,433 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,437 INFO sqlalchemy.engine.base.Engine ('2019-03-26', 3212, 274, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,441 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,441 INFO sqlalchemy.engine.base.Engine ('2019-03-27', 3220, 274, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,446 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,448 INFO sqlalchemy.engine.base.Engine ('2019-03-28', 3226, 275, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,451 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,452 INFO sqlalchemy.engine.base.Engine ('2019-03-29', 3241, 275, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,454 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,456 INFO sqlalchemy.engine.base.Engine ('2019-03-30', 3253, 278, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,456 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,460 INFO sqlalchemy.engine.base.Engine ('2019-03-31', 3255, 278, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,460 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,464 INFO sqlalchemy.engine.base.Engine ('2019-04-01', 3258, 280, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,464 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,464 INFO sqlalchemy.engine.base.Engine ('2019-04-02', 3262, 282, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,468 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,468 INFO sqlalchemy.engine.base.Engine ('2019-04-03', 3264, 282, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,472 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,472 INFO sqlalchemy.engine.base.Engine ('2019-04-04', 3272, 282, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,476 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,476 INFO sqlalchemy.engine.base.Engine ('2019-04-05', 3275, 284, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,480 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,480 INFO sqlalchemy.engine.base.Engine ('2019-04-06', 3276, 287, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,484 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,488 INFO sqlalchemy.engine.base.Engine ('2019-04-07', 3279, 289, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,488 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,492 INFO sqlalchemy.engine.base.Engine ('2019-04-08', 3285, 289, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,492 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,496 INFO sqlalchemy.engine.base.Engine ('2019-04-09', 3300, 291, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,500 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,500 INFO sqlalchemy.engine.base.Engine ('2019-04-10', 3306, 293, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,504 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,504 INFO sqlalchemy.engine.base.Engine ('2019-04-11', 3312, 295, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,508 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,508 INFO sqlalchemy.engine.base.Engine ('2019-04-12', 3319, 295, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,508 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,512 INFO sqlalchemy.engine.base.Engine ('2019-04-13', 3324, 295, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,512 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,516 INFO sqlalchemy.engine.base.Engine ('2019-04-14', 3325, 297, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,520 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,520 INFO sqlalchemy.engine.base.Engine ('2019-04-15', 3329, 298, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,524 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,524 INFO sqlalchemy.engine.base.Engine ('2019-04-16', 3331, 299, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,528 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,528 INFO sqlalchemy.engine.base.Engine ('2019-04-17', 3332, 299, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,532 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,532 INFO sqlalchemy.engine.base.Engine ('2019-04-18', 3333, 299, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,536 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,536 INFO sqlalchemy.engine.base.Engine ('2019-04-19', 3336, 299, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,540 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,540 INFO sqlalchemy.engine.base.Engine ('2019-04-20', 3339, 299, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,544 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,544 INFO sqlalchemy.engine.base.Engine ('2019-04-21', 3343, 300, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,548 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,548 INFO sqlalchemy.engine.base.Engine ('2019-04-22', 3349, 302, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,552 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,552 INFO sqlalchemy.engine.base.Engine ('2019-04-23', 3357, 303, '2020-08-26 06:45:17.772911')

2020-08-26 06:45:22,556 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,556 INFO sqlalchemy.engine.base.Engine ('2019-04-24', 3370, 303, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,560 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,564 INFO sqlalchemy.engine.base.Engine ('2019-04-25', 3388, 304, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,564 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,564 INFO sqlalchemy.engine.base.Engine ('2019-04-26', 3412, 304, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,568 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,568 INFO sqlalchemy.engine.base.Engine ('2019-04-27', 3437, 305, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,572 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,572 INFO sqlalchemy.engine.base.Engine ('2019-04-28', 3439, 305, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,576 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,577 INFO sqlalchemy.engine.base.Engine ('2019-04-29', 3440, 308, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,581 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,581 INFO sqlalchemy.engine.base.Engine ('2019-04-30', 3447, 309, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,585 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,585 INFO sqlalchemy.engine.base.Engine ('2019-05-01', 3466, 310, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,589 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,589 INFO sqlalchemy.engine.base.Engine ('2019-05-02', 3481, 311, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,593 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,593 INFO sqlalchemy.engine.base.Engine ('2019-05-03', 3504, 314, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,597 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,597 INFO sqlalchemy.engine.base.Engine ('2019-05-04', 3522, 317, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,601 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,601 INFO sqlalchemy.engine.base.Engine ('2019-05-05', 3527, 322, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,601 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,605 INFO sqlalchemy.engine.base.Engine ('2019-05-06', 3533, 324, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,605 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,605 INFO sqlalchemy.engine.base.Engine ('2019-05-07', 3543, 327, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,609 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,613 INFO sqlalchemy.engine.base.Engine ('2019-05-08', 3546, 328, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,613 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,617 INFO sqlalchemy.engine.base.Engine ('2019-05-09', 3555, 330, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,617 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,621 INFO sqlalchemy.engine.base.Engine ('2019-05-10', 3566, 332, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,621 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,625 INFO sqlalchemy.engine.base.Engine ('2019-05-11', 3583, 334, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,625 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,629 INFO sqlalchemy.engine.base.Engine ('2019-05-12', 3594, 335, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,629 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,633 INFO sqlalchemy.engine.base.Engine ('2019-05-13', 3614, 338, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,633 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,633 INFO sqlalchemy.engine.base.Engine ('2019-05-14', 3633, 340, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,637 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,637 INFO sqlalchemy.engine.base.Engine ('2019-05-15', 3647, 344, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,641 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,641 INFO sqlalchemy.engine.base.Engine ('2019-05-16', 3648, 349, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,645 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,645 INFO sqlalchemy.engine.base.Engine ('2019-05-17', 3649, 349, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,645 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,649 INFO sqlalchemy.engine.base.Engine ('2019-05-18', 3651, 351, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,649 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,653 INFO sqlalchemy.engine.base.Engine ('2019-05-19', 3654, 351, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,657 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,657 INFO sqlalchemy.engine.base.Engine ('2019-05-20', 3658, 354, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,657 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,661 INFO sqlalchemy.engine.base.Engine ('2019-05-21', 3671, 354, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,665 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,665 INFO sqlalchemy.engine.base.Engine ('2019-05-22', 3675, 359, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,665 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,669 INFO sqlalchemy.engine.base.Engine ('2019-05-23', 3681, 359, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,669 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,669 INFO sqlalchemy.engine.base.Engine ('2019-05-24', 3694, 361, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,673 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,677 INFO sqlalchemy.engine.base.Engine ('2019-05-25', 3699, 361, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,677 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,681 INFO sqlalchemy.engine.base.Engine ('2019-05-26', 3711, 364, '2020-08-26 06:45:17.772911')

2020-08-26 06:45:22,681 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,685 INFO sqlalchemy.engine.base.Engine ('2019-05-27', 3722, 368, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,685 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,689 INFO sqlalchemy.engine.base.Engine ('2019-05-28', 3734, 373, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,693 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,693 INFO sqlalchemy.engine.base.Engine ('2019-05-29', 3766, 374, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,693 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,697 INFO sqlalchemy.engine.base.Engine ('2019-05-30', 3781, 375, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,697 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,701 INFO sqlalchemy.engine.base.Engine ('2019-05-31', 3784, 375, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,701 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,705 INFO sqlalchemy.engine.base.Engine ('2019-06-01', 3789, 378, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,709 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,709 INFO sqlalchemy.engine.base.Engine ('2019-06-02', 3790, 379, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,713 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,713 INFO sqlalchemy.engine.base.Engine ('2019-06-03', 3793, 380, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,717 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,717 INFO sqlalchemy.engine.base.Engine ('2019-06-04', 3795, 383, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,721 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,721 INFO sqlalchemy.engine.base.Engine ('2019-06-05', 3808, 385, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,725 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,725 INFO sqlalchemy.engine.base.Engine ('2019-06-06', 3830, 386, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,729 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,733 INFO sqlalchemy.engine.base.Engine ('2019-06-07', 3843, 387, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,733 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,737 INFO sqlalchemy.engine.base.Engine ('2019-06-08', 3857, 390, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,737 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,741 INFO sqlalchemy.engine.base.Engine ('2019-06-09', 3870, 394, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,741 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,745 INFO sqlalchemy.engine.base.Engine ('2019-06-10', 3895, 395, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,749 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,749 INFO sqlalchemy.engine.base.Engine ('2019-06-11', 3919, 397, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,753 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,753 INFO sqlalchemy.engine.base.Engine ('2019-06-12', 3942, 399, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,757 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,757 INFO sqlalchemy.engine.base.Engine ('2019-06-13', 3983, 402, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,761 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,765 INFO sqlalchemy.engine.base.Engine ('2019-06-14', 4022, 404, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,765 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,765 INFO sqlalchemy.engine.base.Engine ('2019-06-15', 4053, 409, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,769 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,769 INFO sqlalchemy.engine.base.Engine ('2019-06-16', 4058, 410, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,773 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,773 INFO sqlalchemy.engine.base.Engine ('2019-06-17', 4063, 414, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,777 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,781 INFO sqlalchemy.engine.base.Engine ('2019-06-18', 4064, 417, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,785 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,785 INFO sqlalchemy.engine.base.Engine ('2019-06-19', 4065, 422, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,789 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,789 INFO sqlalchemy.engine.base.Engine ('2019-06-20', 4066, 424, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,793 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,797 INFO sqlalchemy.engine.base.Engine ('2019-06-21', 4069, 425, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,797 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,801 INFO sqlalchemy.engine.base.Engine ('2019-06-22', 4070, 426, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,801 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,805 INFO sqlalchemy.engine.base.Engine ('2019-06-23', 4073, 427, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,805 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,809 INFO sqlalchemy.engine.base.Engine ('2019-06-24', 4084, 427, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,813 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,813 INFO sqlalchemy.engine.base.Engine ('2019-06-25', 4108, 427, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,817 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,821 INFO sqlalchemy.engine.base.Engine ('2019-06-26', 4122, 433, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,821 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,825 INFO sqlalchemy.engine.base.Engine ('2019-06-27', 4132, 436, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,829 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,829 INFO sqlalchemy.engine.base.Engine ('2019-06-28', 4150, 440, '2020-08-26 06:45:17.772911')

2020-08-26 06:45:22,833 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,833 INFO sqlalchemy.engine.base.Engine ('2019-06-29', 4162, 440, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,837 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,837 INFO sqlalchemy.engine.base.Engine ('2019-06-30', 4164, 446, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,841 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,841 INFO sqlalchemy.engine.base.Engine ('2019-07-01', 4167, 448, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,845 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,845 INFO sqlalchemy.engine.base.Engine ('2019-07-02', 4174, 450, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,849 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,853 INFO sqlalchemy.engine.base.Engine ('2019-07-03', 4179, 455, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,853 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,853 INFO sqlalchemy.engine.base.Engine ('2019-07-04', 4187, 456, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,857 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,861 INFO sqlalchemy.engine.base.Engine ('2019-07-05', 4200, 456, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,861 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,865 INFO sqlalchemy.engine.base.Engine ('2019-07-06', 4210, 458, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,865 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,869 INFO sqlalchemy.engine.base.Engine ('2019-07-07', 4211, 458, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,869 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,873 INFO sqlalchemy.engine.base.Engine ('2019-07-08', 4214, 464, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,873 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,877 INFO sqlalchemy.engine.base.Engine ('2019-07-09', 4219, 464, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,881 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,881 INFO sqlalchemy.engine.base.Engine ('2019-07-10', 4223, 468, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,885 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,885 INFO sqlalchemy.engine.base.Engine ('2019-07-11', 4228, 469, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,889 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,889 INFO sqlalchemy.engine.base.Engine ('2019-07-12', 4236, 469, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,893 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,893 INFO sqlalchemy.engine.base.Engine ('2019-07-13', 4239, 471, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,897 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,897 INFO sqlalchemy.engine.base.Engine ('2019-07-14', 4243, 471, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,901 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,901 INFO sqlalchemy.engine.base.Engine ('2019-07-15', 4250, 473, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,905 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,909 INFO sqlalchemy.engine.base.Engine ('2019-07-16', 4265, 476, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,909 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,913 INFO sqlalchemy.engine.base.Engine ('2019-07-17', 4288, 476, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,917 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,917 INFO sqlalchemy.engine.base.Engine ('2019-07-18', 4313, 483, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,921 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,921 INFO sqlalchemy.engine.base.Engine ('2019-07-19', 4329, 483, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,925 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,925 INFO sqlalchemy.engine.base.Engine ('2019-07-20', 4329, 486, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,929 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,929 INFO sqlalchemy.engine.base.Engine ('2019-07-21', 4329, 487, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,933 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,933 INFO sqlalchemy.engine.base.Engine ('2019-07-22', 4333, 492, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,937 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,937 INFO sqlalchemy.engine.base.Engine ('2019-07-23', 4335, 493, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,937 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,941 INFO sqlalchemy.engine.base.Engine ('2019-07-24', 4353, 494, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,945 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,945 INFO sqlalchemy.engine.base.Engine ('2019-07-25', 4370, 496, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,949 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,949 INFO sqlalchemy.engine.base.Engine ('2019-07-26', 4397, 500, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,953 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,957 INFO sqlalchemy.engine.base.Engine ('2019-07-27', 4419, 504, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,957 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,961 INFO sqlalchemy.engine.base.Engine ('2019-07-28', 4422, 507, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,965 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,965 INFO sqlalchemy.engine.base.Engine ('2019-07-29', 4423, 513, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,969 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,969 INFO sqlalchemy.engine.base.Engine ('2019-07-30', 4425, 516, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,973 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,981 INFO sqlalchemy.engine.base.Engine ('2019-07-31', 4427, 518, '2020-08-26 06:45:17.772911')

2020-08-26 06:45:22,985 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,985 INFO sqlalchemy.engine.base.Engine ('2019-08-01', 4432, 519, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,989 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,989 INFO sqlalchemy.engine.base.Engine ('2019-08-02', 4433, 520, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:22,993 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:22,997 INFO sqlalchemy.engine.base.Engine ('2019-08-03', 4435, 522, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,001 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,005 INFO sqlalchemy.engine.base.Engine ('2019-08-04', 4437, 522, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,009 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,013 INFO sqlalchemy.engine.base.Engine ('2019-08-05', 4440, 526, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,013 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,017 INFO sqlalchemy.engine.base.Engine ('2019-08-06', 4444, 528, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,017 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,021 INFO sqlalchemy.engine.base.Engine ('2019-08-07', 4452, 528, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,021 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,021 INFO sqlalchemy.engine.base.Engine ('2019-08-08', 4466, 529, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,025 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,025 INFO sqlalchemy.engine.base.Engine ('2019-08-09', 4493, 529, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,033 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,033 INFO sqlalchemy.engine.base.Engine ('2019-08-10', 4521, 530, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,037 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,037 INFO sqlalchemy.engine.base.Engine ('2019-08-11', 4528, 531, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,041 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,041 INFO sqlalchemy.engine.base.Engine ('2019-08-12', 4529, 533, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,045 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,049 INFO sqlalchemy.engine.base.Engine ('2019-08-13', 4532, 534, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,049 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,053 INFO sqlalchemy.engine.base.Engine ('2019-08-14', 4534, 537, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,053 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,057 INFO sqlalchemy.engine.base.Engine ('2019-08-15', 4535, 537, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,057 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,057 INFO sqlalchemy.engine.base.Engine ('2019-08-16', 4539, 539, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,061 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,061 INFO sqlalchemy.engine.base.Engine ('2019-08-17', 4539, 540, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,065 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,065 INFO sqlalchemy.engine.base.Engine ('2019-08-18', 4541, 541, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,069 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,073 INFO sqlalchemy.engine.base.Engine ('2019-08-19', 4545, 544, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,073 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,077 INFO sqlalchemy.engine.base.Engine ('2019-08-20', 4545, 545, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,081 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,081 INFO sqlalchemy.engine.base.Engine ('2019-08-21', 4561, 548, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,085 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,085 INFO sqlalchemy.engine.base.Engine ('2019-08-22', 4590, 549, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,089 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,089 INFO sqlalchemy.engine.base.Engine ('2019-08-23', 4624, 549, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,093 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,093 INFO sqlalchemy.engine.base.Engine ('2019-08-24', 4641, 552, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,097 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,097 INFO sqlalchemy.engine.base.Engine ('2019-08-25', 4665, 554, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,101 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,101 INFO sqlalchemy.engine.base.Engine ('2019-08-26', 4702, 557, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,105 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,109 INFO sqlalchemy.engine.base.Engine ('2019-08-27', 4730, 561, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,113 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,113 INFO sqlalchemy.engine.base.Engine ('2019-08-28', 4761, 564, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,117 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,121 INFO sqlalchemy.engine.base.Engine ('2019-08-29', 4793, 566, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,125 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,125 INFO sqlalchemy.engine.base.Engine ('2019-08-30', 4846, 566, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,129 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,133 INFO sqlalchemy.engine.base.Engine ('2019-08-31', 4878, 571, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,137 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,137 INFO sqlalchemy.engine.base.Engine ('2019-09-01', 4884, 572, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,141 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,141 INFO sqlalchemy.engine.base.Engine ('2019-09-02', 4888, 573, '2020-08-26 06:45:17.772911')

2020-08-26 06:45:23,145 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,149 INFO sqlalchemy.engine.base.Engine ('2019-09-03', 4887, 574, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,149 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,153 INFO sqlalchemy.engine.base.Engine ('2019-09-04', 4888, 575, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,157 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,157 INFO sqlalchemy.engine.base.Engine ('2019-09-05', 4890, 577, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,161 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,161 INFO sqlalchemy.engine.base.Engine ('2019-09-06', 4892, 577, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,165 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,165 INFO sqlalchemy.engine.base.Engine ('2019-09-07', 4894, 578, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,205 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,209 INFO sqlalchemy.engine.base.Engine ('2019-09-08', 4896, 578, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,209 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,213 INFO sqlalchemy.engine.base.Engine ('2019-09-09', 4907, 579, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,213 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,217 INFO sqlalchemy.engine.base.Engine ('2019-09-10', 4918, 581, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,217 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,217 INFO sqlalchemy.engine.base.Engine ('2019-09-11', 4935, 583, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,221 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,225 INFO sqlalchemy.engine.base.Engine ('2019-09-12', 4949, 583, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,225 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,229 INFO sqlalchemy.engine.base.Engine ('2019-09-13', 4965, 584, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,229 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,233 INFO sqlalchemy.engine.base.Engine ('2019-09-14', 4966, 587, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,233 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,233 INFO sqlalchemy.engine.base.Engine ('2019-09-15', 4966, 587, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,237 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,237 INFO sqlalchemy.engine.base.Engine ('2019-09-16', 4970, 590, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,241 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,245 INFO sqlalchemy.engine.base.Engine ('2019-09-17', 4972, 590, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,245 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,249 INFO sqlalchemy.engine.base.Engine ('2019-09-18', 4974, 592, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,249 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,249 INFO sqlalchemy.engine.base.Engine ('2019-09-19', 4996, 596, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,253 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,253 INFO sqlalchemy.engine.base.Engine ('2019-09-20', 4998, 601, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,257 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,257 INFO sqlalchemy.engine.base.Engine ('2019-09-21', 5001, 601, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,261 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,261 INFO sqlalchemy.engine.base.Engine ('2019-09-22', 5004, 603, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,265 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,265 INFO sqlalchemy.engine.base.Engine ('2019-09-23', 5005, 605, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,269 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,273 INFO sqlalchemy.engine.base.Engine ('2019-09-24', 5012, 605, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,273 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,273 INFO sqlalchemy.engine.base.Engine ('2019-09-25', 5023, 609, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,277 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,281 INFO sqlalchemy.engine.base.Engine ('2019-09-26', 5033, 609, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,281 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,281 INFO sqlalchemy.engine.base.Engine ('2019-09-27', 5068, 612, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,285 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,285 INFO sqlalchemy.engine.base.Engine ('2019-09-28', 5084, 613, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,289 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,289 INFO sqlalchemy.engine.base.Engine ('2019-09-29', 5088, 614, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,293 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,293 INFO sqlalchemy.engine.base.Engine ('2019-09-30', 5097, 615, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,297 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,297 INFO sqlalchemy.engine.base.Engine ('2019-10-01', 5113, 617, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,301 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,301 INFO sqlalchemy.engine.base.Engine ('2019-10-02', 5117, 618, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,305 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,305 INFO sqlalchemy.engine.base.Engine ('2019-10-03', 5120, 620, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,309 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,309 INFO sqlalchemy.engine.base.Engine ('2019-10-04', 5128, 622, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,313 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,313 INFO sqlalchemy.engine.base.Engine ('2019-10-05', 5133, 624, '2020-08-26 06:45:17.772911')

2020-08-26 06:45:23,313 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,317 INFO sqlalchemy.engine.base.Engine ('2019-10-06', 5137, 628, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,317 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,321 INFO sqlalchemy.engine.base.Engine ('2019-10-07', 5144, 630, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,321 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,325 INFO sqlalchemy.engine.base.Engine ('2019-10-08', 5160, 633, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,325 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,329 INFO sqlalchemy.engine.base.Engine ('2019-10-09', 5166, 637, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,329 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,333 INFO sqlalchemy.engine.base.Engine ('2019-10-10', 5167, 639, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,333 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,337 INFO sqlalchemy.engine.base.Engine ('2019-10-11', 5168, 641, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,337 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,341 INFO sqlalchemy.engine.base.Engine ('2019-10-12', 5169, 644, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,345 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,345 INFO sqlalchemy.engine.base.Engine ('2019-10-13', 5170, 646, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,349 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,349 INFO sqlalchemy.engine.base.Engine ('2019-10-14', 5170, 649, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,349 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,353 INFO sqlalchemy.engine.base.Engine ('2019-10-15', 5179, 651, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,353 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,357 INFO sqlalchemy.engine.base.Engine ('2019-10-16', 5185, 651, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,357 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,357 INFO sqlalchemy.engine.base.Engine ('2019-10-17', 5187, 652, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,361 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,365 INFO sqlalchemy.engine.base.Engine ('2019-10-18', 5189, 653, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,369 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,369 INFO sqlalchemy.engine.base.Engine ('2019-10-19', 5191, 654, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,369 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,373 INFO sqlalchemy.engine.base.Engine ('2019-10-20', 5193, 655, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,373 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,377 INFO sqlalchemy.engine.base.Engine ('2019-10-21', 5194, 656, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,377 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,381 INFO sqlalchemy.engine.base.Engine ('2019-10-22', 5197, 658, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,381 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,385 INFO sqlalchemy.engine.base.Engine ('2019-10-23', 5210, 659, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,385 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,389 INFO sqlalchemy.engine.base.Engine ('2019-10-24', 5223, 663, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,389 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,393 INFO sqlalchemy.engine.base.Engine ('2019-10-25', 5232, 663, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,393 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,397 INFO sqlalchemy.engine.base.Engine ('2019-10-26', 5233, 664, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,397 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,397 INFO sqlalchemy.engine.base.Engine ('2019-10-27', 5234, 665, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,401 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,405 INFO sqlalchemy.engine.base.Engine ('2019-10-28', 5236, 666, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,405 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,409 INFO sqlalchemy.engine.base.Engine ('2019-10-29', 5240, 670, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,409 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,413 INFO sqlalchemy.engine.base.Engine ('2019-10-30', 5242, 671, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,413 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,413 INFO sqlalchemy.engine.base.Engine ('2019-10-31', 5243, 671, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,417 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,417 INFO sqlalchemy.engine.base.Engine ('2019-11-01', 5244, 674, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,421 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,421 INFO sqlalchemy.engine.base.Engine ('2019-11-02', 5246, 674, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,425 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,429 INFO sqlalchemy.engine.base.Engine ('2019-11-03', 5246, 676, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,429 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,433 INFO sqlalchemy.engine.base.Engine ('2019-11-04', 5247, 676, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,433 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,437 INFO sqlalchemy.engine.base.Engine ('2019-11-06', 5269, 679, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,437 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,441 INFO sqlalchemy.engine.base.Engine ('2019-11-07', 5284, 681, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,445 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,445 INFO sqlalchemy.engine.base.Engine ('2019-11-08', 5298, 683, '2020-08-26 06:45:17.772911')

2020-08-26 06:45:23,449 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,449 INFO sqlalchemy.engine.base.Engine ('2019-11-09', 5307, 684, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,453 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,453 INFO sqlalchemy.engine.base.Engine ('2019-11-10', 5313, 687, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,457 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,461 INFO sqlalchemy.engine.base.Engine ('2019-11-11', 5314, 687, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,465 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,465 INFO sqlalchemy.engine.base.Engine ('2019-11-12', 5314, 688, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,469 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,469 INFO sqlalchemy.engine.base.Engine ('2019-11-13', 5316, 689, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,473 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,473 INFO sqlalchemy.engine.base.Engine ('2019-11-14', 5326, 691, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,477 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,481 INFO sqlalchemy.engine.base.Engine ('2019-11-15', 5337, 691, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,486 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,488 INFO sqlalchemy.engine.base.Engine ('2019-11-16', 5338, 692, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,491 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,492 INFO sqlalchemy.engine.base.Engine ('2019-11-17', 5342, 692, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,496 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,496 INFO sqlalchemy.engine.base.Engine ('2019-11-18', 5343, 695, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,500 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,504 INFO sqlalchemy.engine.base.Engine ('2019-11-19', 5347, 697, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,504 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,508 INFO sqlalchemy.engine.base.Engine ('2019-11-20', 5348, 697, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,512 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,512 INFO sqlalchemy.engine.base.Engine ('2019-11-21', 5351, 700, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,516 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,520 INFO sqlalchemy.engine.base.Engine ('2019-11-22', 5356, 700, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,524 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,524 INFO sqlalchemy.engine.base.Engine ('2019-11-23', 5383, 700, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,528 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,532 INFO sqlalchemy.engine.base.Engine ('2019-11-24', 5409, 704, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,532 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,536 INFO sqlalchemy.engine.base.Engine ('2019-11-25', 5435, 709, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,540 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,540 INFO sqlalchemy.engine.base.Engine ('2019-11-26', 5450, 714, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,540 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,544 INFO sqlalchemy.engine.base.Engine ('2019-11-27', 5479, 714, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,548 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,552 INFO sqlalchemy.engine.base.Engine ('2019-11-28', 5503, 715, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,552 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,556 INFO sqlalchemy.engine.base.Engine ('2019-11-29', 5554, 716, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,556 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,560 INFO sqlalchemy.engine.base.Engine ('2019-11-30', 5643, 718, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,564 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,564 INFO sqlalchemy.engine.base.Engine ('2019-12-01', 5652, 720, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,568 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,572 INFO sqlalchemy.engine.base.Engine ('2019-12-02', 5654, 723, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,576 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,576 INFO sqlalchemy.engine.base.Engine ('2019-12-03', 5678, 723, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,580 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,584 INFO sqlalchemy.engine.base.Engine ('2019-12-04', 5706, 723, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,584 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,584 INFO sqlalchemy.engine.base.Engine ('2019-12-05', 5747, 726, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,588 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,588 INFO sqlalchemy.engine.base.Engine ('2019-12-06', 5802, 728, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,592 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,596 INFO sqlalchemy.engine.base.Engine ('2019-12-07', 5807, 728, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,600 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,600 INFO sqlalchemy.engine.base.Engine ('2019-12-08', 5811, 732, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,604 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,604 INFO sqlalchemy.engine.base.Engine ('2019-12-09', 5811, 732, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,608 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,608 INFO sqlalchemy.engine.base.Engine ('2019-12-10', 5813, 735, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,612 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,616 INFO sqlalchemy.engine.base.Engine ('2019-12-11', 5819, 735, '2020-08-26 06:45:17.772911')

2020-08-26 06:45:23,620 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,620 INFO sqlalchemy.engine.base.Engine ('2019-12-12', 5825, 737, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,624 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,625 INFO sqlalchemy.engine.base.Engine ('2019-12-13', 5830, 739, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,629 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,629 INFO sqlalchemy.engine.base.Engine ('2019-12-14', 5833, 739, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,633 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,633 INFO sqlalchemy.engine.base.Engine ('2019-12-15', 5837, 740, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,637 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,637 INFO sqlalchemy.engine.base.Engine ('2019-12-16', 5839, 742, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,641 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,641 INFO sqlalchemy.engine.base.Engine ('2019-12-17', 5840, 744, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,645 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,645 INFO sqlalchemy.engine.base.Engine ('2019-12-18', 5846, 745, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,649 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,653 INFO sqlalchemy.engine.base.Engine ('2019-12-19', 5847, 745, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,653 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,657 INFO sqlalchemy.engine.base.Engine ('2019-12-20', 5849, 746, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,657 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,661 INFO sqlalchemy.engine.base.Engine ('2019-12-21', 5850, 746, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,665 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,665 INFO sqlalchemy.engine.base.Engine ('2019-12-22', 5852, 746, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,669 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,669 INFO sqlalchemy.engine.base.Engine ('2019-12-23', 5870, 747, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,673 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,673 INFO sqlalchemy.engine.base.Engine ('2019-12-24', 5878, 748, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,679 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,681 INFO sqlalchemy.engine.base.Engine ('2019-12-25', 5888, 748, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,685 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,686 INFO sqlalchemy.engine.base.Engine ('2019-12-26', 5906, 749, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,688 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,688 INFO sqlalchemy.engine.base.Engine ('2019-12-27', 5927, 749, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,692 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,696 INFO sqlalchemy.engine.base.Engine ('2019-12-28', 5930, 749, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,700 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,700 INFO sqlalchemy.engine.base.Engine ('2019-12-29', 5933, 750, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,704 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,704 INFO sqlalchemy.engine.base.Engine ('2019-12-30', 5936, 752, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,708 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,716 INFO sqlalchemy.engine.base.Engine ('2019-12-31', 5937, 753, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,716 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,720 INFO sqlalchemy.engine.base.Engine ('2020-01-01', 5964, 760, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,720 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,724 INFO sqlalchemy.engine.base.Engine ('2020-01-02', 5989, 764, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,732 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,732 INFO sqlalchemy.engine.base.Engine ('2020-01-03', 5999, 768, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,736 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,736 INFO sqlalchemy.engine.base.Engine ('2020-01-04', 6011, 768, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,740 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,744 INFO sqlalchemy.engine.base.Engine ('2020-01-05', 6023, 771, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,748 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,752 INFO sqlalchemy.engine.base.Engine ('2020-01-06', 6042, 772, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,756 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,756 INFO sqlalchemy.engine.base.Engine ('2020-01-07', 6060, 776, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,760 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,760 INFO sqlalchemy.engine.base.Engine ('2020-01-08', 6089, 778, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,764 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,768 INFO sqlalchemy.engine.base.Engine ('2020-01-09', 6121, 780, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,772 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,772 INFO sqlalchemy.engine.base.Engine ('2020-01-10', 6174, 781, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,776 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,776 INFO sqlalchemy.engine.base.Engine ('2020-01-11', 6178, 782, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,845 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,849 INFO sqlalchemy.engine.base.Engine ('2020-01-12', 6182, 784, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,853 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,853 INFO sqlalchemy.engine.base.Engine ('2020-01-13', 6188, 784, '2020-08-26 06:45:17.772911')

2020-08-26 06:45:23,857 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,857 INFO sqlalchemy.engine.base.Engine ('2020-01-14', 6191, 788, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,861 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,865 INFO sqlalchemy.engine.base.Engine ('2020-01-15', 6193, 792, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,869 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,869 INFO sqlalchemy.engine.base.Engine ('2020-01-16', 6196, 793, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,873 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,873 INFO sqlalchemy.engine.base.Engine ('2020-01-17', 6201, 793, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,877 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,877 INFO sqlalchemy.engine.base.Engine ('2020-01-18', 6200, 795, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,881 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,881 INFO sqlalchemy.engine.base.Engine ('2020-01-19', 6204, 797, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,885 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,885 INFO sqlalchemy.engine.base.Engine ('2020-01-20', 6206, 801, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,889 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,889 INFO sqlalchemy.engine.base.Engine ('2020-01-21', 6212, 803, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,893 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,893 INFO sqlalchemy.engine.base.Engine ('2020-01-22', 6213, 806, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,897 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,901 INFO sqlalchemy.engine.base.Engine ('2020-01-23', 6215, 808, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,901 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,905 INFO sqlalchemy.engine.base.Engine ('2020-01-24', 6219, 808, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,905 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,909 INFO sqlalchemy.engine.base.Engine ('2020-01-25', 6222, 811, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,909 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,913 INFO sqlalchemy.engine.base.Engine ('2020-01-26', 6223, 811, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,917 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,917 INFO sqlalchemy.engine.base.Engine ('2020-01-27', 6224, 811, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,921 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,921 INFO sqlalchemy.engine.base.Engine ('2020-01-28', 6229, 812, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,925 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,925 INFO sqlalchemy.engine.base.Engine ('2020-01-29', 6248, 812, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,929 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,933 INFO sqlalchemy.engine.base.Engine ('2020-01-30', 6281, 813, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,937 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,937 INFO sqlalchemy.engine.base.Engine ('2020-01-31', 6286, 816, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,937 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,942 INFO sqlalchemy.engine.base.Engine ('2020-02-01', 6291, 820, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,942 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,946 INFO sqlalchemy.engine.base.Engine ('2020-02-02', 6294, 820, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,950 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,954 INFO sqlalchemy.engine.base.Engine ('2020-02-03', 6299, 820, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,954 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,958 INFO sqlalchemy.engine.base.Engine ('2020-02-04', 6310, 821, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,962 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,966 INFO sqlalchemy.engine.base.Engine ('2020-02-05', 6319, 824, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,966 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,970 INFO sqlalchemy.engine.base.Engine ('2020-02-06', 6337, 827, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,970 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,974 INFO sqlalchemy.engine.base.Engine ('2020-02-07', 6352, 829, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,974 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,978 INFO sqlalchemy.engine.base.Engine ('2020-02-08', 6353, 833, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,982 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,986 INFO sqlalchemy.engine.base.Engine ('2020-02-09', 6356, 834, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,986 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,990 INFO sqlalchemy.engine.base.Engine ('2020-02-10', 6359, 836, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,990 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,994 INFO sqlalchemy.engine.base.Engine ('2020-02-11', 6361, 843, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:23,998 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:23,998 INFO sqlalchemy.engine.base.Engine ('2020-02-12', 6366, 845, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,002 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,006 INFO sqlalchemy.engine.base.Engine ('2020-02-13', 6370, 848, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,006 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,006 INFO sqlalchemy.engine.base.Engine ('2020-02-14', 6387, 852, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,010 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,014 INFO sqlalchemy.engine.base.Engine ('2020-02-15', 6399, 854, '2020-08-26 06:45:17.772911')

2020-08-26 06:45:24,018 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,018 INFO sqlalchemy.engine.base.Engine ('2020-02-16', 6399, 854, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,022 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,022 INFO sqlalchemy.engine.base.Engine ('2020-02-17', 6407, 857, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,026 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,026 INFO sqlalchemy.engine.base.Engine ('2020-02-18', 6411, 860, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,034 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,036 INFO sqlalchemy.engine.base.Engine ('2020-02-19', 6412, 861, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,038 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,039 INFO sqlalchemy.engine.base.Engine ('2020-02-20', 6413, 861, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,041 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,042 INFO sqlalchemy.engine.base.Engine ('2020-02-21', 6428, 862, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,046 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,050 INFO sqlalchemy.engine.base.Engine ('2020-02-22', 6436, 862, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,050 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,054 INFO sqlalchemy.engine.base.Engine ('2020-02-23', 6439, 867, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,054 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,058 INFO sqlalchemy.engine.base.Engine ('2020-02-24', 6442, 868, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,062 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,066 INFO sqlalchemy.engine.base.Engine ('2020-02-25', 6455, 869, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,070 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,070 INFO sqlalchemy.engine.base.Engine ('2020-02-26', 6460, 871, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,074 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,078 INFO sqlalchemy.engine.base.Engine ('2020-02-27', 6470, 872, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,082 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,086 INFO sqlalchemy.engine.base.Engine ('2020-02-28', 6482, 873, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,086 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,090 INFO sqlalchemy.engine.base.Engine ('2020-02-29', 6495, 876, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,090 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,094 INFO sqlalchemy.engine.base.Engine ('2020-03-01', 6500, 876, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,094 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,098 INFO sqlalchemy.engine.base.Engine ('2020-03-02', 6504, 878, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,098 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,102 INFO sqlalchemy.engine.base.Engine ('2020-03-03', 6510, 885, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,106 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,106 INFO sqlalchemy.engine.base.Engine ('2020-03-04', 6519, 890, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,106 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,110 INFO sqlalchemy.engine.base.Engine ('2020-03-05', 6527, 893, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,114 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,114 INFO sqlalchemy.engine.base.Engine ('2020-03-06', 6534, 894, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,118 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,118 INFO sqlalchemy.engine.base.Engine ('2020-03-07', 6539, 894, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,122 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,122 INFO sqlalchemy.engine.base.Engine ('2020-03-08', 6549, 897, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,126 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,130 INFO sqlalchemy.engine.base.Engine ('2020-03-09', 6568, 897, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,130 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,134 INFO sqlalchemy.engine.base.Engine ('2020-03-10', 6590, 902, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,134 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,138 INFO sqlalchemy.engine.base.Engine ('2020-03-11', 6609, 906, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,138 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,142 INFO sqlalchemy.engine.base.Engine ('2020-03-12', 6636, 909, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,142 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,146 INFO sqlalchemy.engine.base.Engine ('2020-03-13', 6640, 909, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,150 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,150 INFO sqlalchemy.engine.base.Engine ('2020-03-14', 6645, 911, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,154 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,154 INFO sqlalchemy.engine.base.Engine ('2020-03-15', 6649, 916, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,158 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,158 INFO sqlalchemy.engine.base.Engine ('2020-03-16', 6652, 920, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,162 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,162 INFO sqlalchemy.engine.base.Engine ('2020-03-17', 6672, 922, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,166 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,166 INFO sqlalchemy.engine.base.Engine ('2020-03-18', 6687, 926, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,170 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,170 INFO sqlalchemy.engine.base.Engine ('2020-03-19', 6707, 928, '2020-08-26 06:45:17.772911')

2020-08-26 06:45:24,174 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,178 INFO sqlalchemy.engine.base.Engine ('2020-03-20', 6729, 933, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,178 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,182 INFO sqlalchemy.engine.base.Engine ('2020-03-21', 6764, 934, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,182 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,186 INFO sqlalchemy.engine.base.Engine ('2020-03-22', 6771, 939, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,186 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,190 INFO sqlalchemy.engine.base.Engine ('2020-03-23', 6776, 943, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,190 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,194 INFO sqlalchemy.engine.base.Engine ('2020-03-24', 6783, 948, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,198 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,198 INFO sqlalchemy.engine.base.Engine ('2020-03-25', 6785, 950, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,202 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,202 INFO sqlalchemy.engine.base.Engine ('2020-03-26', 6790, 951, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,206 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,206 INFO sqlalchemy.engine.base.Engine ('2020-03-27', 6792, 952, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,210 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,214 INFO sqlalchemy.engine.base.Engine ('2020-03-28', 6798, 953, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,218 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,218 INFO sqlalchemy.engine.base.Engine ('2020-03-29', 6805, 957, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,222 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,222 INFO sqlalchemy.engine.base.Engine ('2020-03-30', 6809, 958, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,226 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,226 INFO sqlalchemy.engine.base.Engine ('2020-03-31', 6832, 963, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,234 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,239 INFO sqlalchemy.engine.base.Engine ('2020-04-01', 6867, 968, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,239 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,248 INFO sqlalchemy.engine.base.Engine ('2020-04-02', 6868, 974, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,248 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,251 INFO sqlalchemy.engine.base.Engine ('2020-04-03', 6877, 977, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,251 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,256 INFO sqlalchemy.engine.base.Engine ('2020-04-04', 6882, 979, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,264 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,272 INFO sqlalchemy.engine.base.Engine ('2020-04-05', 6886, 979, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,276 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,280 INFO sqlalchemy.engine.base.Engine ('2020-04-06', 6892, 982, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,284 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,284 INFO sqlalchemy.engine.base.Engine ('2020-04-07', 6912, 987, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,288 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,288 INFO sqlalchemy.engine.base.Engine ('2020-04-08', 6913, 991, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,292 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,296 INFO sqlalchemy.engine.base.Engine ('2020-04-09', 6921, 993, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,300 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,300 INFO sqlalchemy.engine.base.Engine ('2020-04-10', 6927, 995, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,304 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,304 INFO sqlalchemy.engine.base.Engine ('2020-04-11', 6938, 996, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,304 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,308 INFO sqlalchemy.engine.base.Engine ('2020-04-12', 6941, 998, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,312 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,312 INFO sqlalchemy.engine.base.Engine ('2020-04-12', 6941, 998, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,316 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,316 INFO sqlalchemy.engine.base.Engine ('2020-04-12', 6941, 998, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,320 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,320 INFO sqlalchemy.engine.base.Engine ('2020-04-12', 6941, 998, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,324 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,324 INFO sqlalchemy.engine.base.Engine ('2020-04-12', 6941, 998, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,324 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,328 INFO sqlalchemy.engine.base.Engine ('2020-04-13', 6948, 1002, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,332 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,336 INFO sqlalchemy.engine.base.Engine ('2020-04-14', 6956, 1006, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,340 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,340 INFO sqlalchemy.engine.base.Engine ('2020-04-15', 6982, 1007, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,344 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,348 INFO sqlalchemy.engine.base.Engine ('2020-04-16', 7003, 1007, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,348 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,352 INFO sqlalchemy.engine.base.Engine ('2020-04-17', 7024, 1012, '2020-08-26 06:45:17.772911')

2020-08-26 06:45:24,352 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,356 INFO sqlalchemy.engine.base.Engine ('2020-04-18', 7050, 1016, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,356 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,360 INFO sqlalchemy.engine.base.Engine ('2020-04-19', 7092, 1017, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,368 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,368 INFO sqlalchemy.engine.base.Engine ('2020-04-20', 7154, 1021, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,372 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,372 INFO sqlalchemy.engine.base.Engine ('2020-04-21', 7233, 1028, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,376 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,376 INFO sqlalchemy.engine.base.Engine ('2020-04-22', 7245, 1031, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,380 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,384 INFO sqlalchemy.engine.base.Engine ('2020-04-23', 7257, 1033, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,388 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,388 INFO sqlalchemy.engine.base.Engine ('2020-04-24', 7265, 1045, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,392 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,400 INFO sqlalchemy.engine.base.Engine ('2020-04-25', 7269, 1048, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,400 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,404 INFO sqlalchemy.engine.base.Engine ('2020-04-26', 7276, 1053, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,404 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,412 INFO sqlalchemy.engine.base.Engine ('2020-04-27', 7281, 1055, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,416 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,420 INFO sqlalchemy.engine.base.Engine ('2020-04-28', 7290, 1059, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,424 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,428 INFO sqlalchemy.engine.base.Engine ('2020-04-29', 7298, 1063, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,432 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,432 INFO sqlalchemy.engine.base.Engine ('2020-04-30', 7353, 1064, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,436 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,440 INFO sqlalchemy.engine.base.Engine ('2020-05-01', 7404, 1069, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,448 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,452 INFO sqlalchemy.engine.base.Engine ('2020-05-02', 7411, 1073, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,452 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,456 INFO sqlalchemy.engine.base.Engine ('2020-05-03', 7423, 1076, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,460 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,464 INFO sqlalchemy.engine.base.Engine ('2020-05-04', 7429, 1080, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,464 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,468 INFO sqlalchemy.engine.base.Engine ('2020-05-05', 7439, 1088, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,468 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,472 INFO sqlalchemy.engine.base.Engine ('2020-05-06', 7487, 1094, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,476 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,476 INFO sqlalchemy.engine.base.Engine ('2020-05-07', 7516, 1105, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,480 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,480 INFO sqlalchemy.engine.base.Engine ('2020-05-08', 7532, 1113, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,484 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,484 INFO sqlalchemy.engine.base.Engine ('2020-05-09', 7557, 1120, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,488 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,492 INFO sqlalchemy.engine.base.Engine ('2020-05-10', 7593, 1126, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,496 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,496 INFO sqlalchemy.engine.base.Engine ('2020-05-11', 7634, 1129, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,500 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,500 INFO sqlalchemy.engine.base.Engine ('2020-05-12', 7664, 1147, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,504 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,504 INFO sqlalchemy.engine.base.Engine ('2020-05-13', 7702, 1154, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,504 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,508 INFO sqlalchemy.engine.base.Engine ('2020-05-14', 7758, 1156, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,508 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,512 INFO sqlalchemy.engine.base.Engine ('2020-05-15', 7823, 1161, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,512 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,516 INFO sqlalchemy.engine.base.Engine ('2020-05-16', 7826, 1167, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,516 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,520 INFO sqlalchemy.engine.base.Engine ('2020-05-17', 7827, 1172, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,520 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,520 INFO sqlalchemy.engine.base.Engine ('2020-05-18', 7831, 1179, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,524 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,524 INFO sqlalchemy.engine.base.Engine ('2020-05-19', 7841, 1180, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,528 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)

2020-08-26 06:45:24,528 INFO sqlalchemy.engine.base.Engine ('2020-05-20', 7842, 1187, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,532 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,532 INFO sqlalchemy.engine.base.Engine ('2020-05-21', 7845, 1189, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,536 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,536 INFO sqlalchemy.engine.base.Engine ('2020-05-22', 7854, 1191, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,536 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,540 INFO sqlalchemy.engine.base.Engine ('2020-05-23', 7861, 1195, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,540 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,544 INFO sqlalchemy.engine.base.Engine ('2020-05-24', 7870, 1200, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,544 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,544 INFO sqlalchemy.engine.base.Engine ('2020-05-25', 7876, 1205, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,548 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,548 INFO sqlalchemy.engine.base.Engine ('2020-05-26', 7884, 1208, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,552 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,552 INFO sqlalchemy.engine.base.Engine ('2020-05-27', 7928, 1212, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,556 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,556 INFO sqlalchemy.engine.base.Engine ('2020-05-28', 7961, 1214, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,556 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,560 INFO sqlalchemy.engine.base.Engine ('2020-05-29', 7969, 1216, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,560 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,560 INFO sqlalchemy.engine.base.Engine ('2020-05-30', 7978, 1219, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,564 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,564 INFO sqlalchemy.engine.base.Engine ('2020-05-31', 7979, 1220, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,568 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,568 INFO sqlalchemy.engine.base.Engine ('2020-06-01', 7979, 1222, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,572 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,572 INFO sqlalchemy.engine.base.Engine ('2020-06-02', 7999, 1226, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,576 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,576 INFO sqlalchemy.engine.base.Engine ('2020-06-03', 8018, 1229, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,580 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,580 INFO sqlalchemy.engine.base.Engine ('2020-06-04', 8040, 1229, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,584 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,584 INFO sqlalchemy.engine.base.Engine ('2020-06-05', 8069, 1238, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,584 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,588 INFO sqlalchemy.engine.base.Engine ('2020-06-06', 8075, 1240, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,588 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,592 INFO sqlalchemy.engine.base.Engine ('2020-06-07', 8080, 1241, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,592 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,596 INFO sqlalchemy.engine.base.Engine ('2020-06-08', 8083, 1246, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,596 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,600 INFO sqlalchemy.engine.base.Engine ('2020-06-09', 8096, 1250, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,600 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,600 INFO sqlalchemy.engine.base.Engine ('2020-06-10', 8104, 1255, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,604 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,604 INFO sqlalchemy.engine.base.Engine ('2020-06-11', 8109, 1260, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,608 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,608 INFO sqlalchemy.engine.base.Engine ('2020-06-12', 8116, 1264, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,612 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,612 INFO sqlalchemy.engine.base.Engine ('2020-06-13', 8143, 1265, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,616 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,616 INFO sqlalchemy.engine.base.Engine ('2020-06-14', 8169, 1269, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,620 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,620 INFO sqlalchemy.engine.base.Engine ('2020-06-15', 8196, 1276, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,624 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,624 INFO sqlalchemy.engine.base.Engine ('2020-06-16', 8201, 1280, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,628 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,632 INFO sqlalchemy.engine.base.Engine ('2020-06-17', 8206, 1283, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,636 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,640 INFO sqlalchemy.engine.base.Engine ('2020-06-18', 8212, 1284, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,644 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,648 INFO sqlalchemy.engine.base.Engine ('2020-06-19', 8217, 1286, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,652 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,656 INFO sqlalchemy.engine.base.Engine ('2020-06-20', 8222, 1289, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,656 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,660 INFO sqlalchemy.engine.base.Engine ('2020-06-21', 8230, 1291, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,664 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)

2020-08-26 06:45:24,664 INFO sqlalchemy.engine.base.Engine ('2020-06-22', 8234, 1295, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,668 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,672 INFO sqlalchemy.engine.base.Engine ('2020-06-23', 8241, 1298, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,676 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,680 INFO sqlalchemy.engine.base.Engine ('2020-06-24', 8246, 1301, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,684 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,684 INFO sqlalchemy.engine.base.Engine ('2020-06-25', 8255, 1305, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,692 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,692 INFO sqlalchemy.engine.base.Engine ('2020-06-26', 8279, 1306, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,696 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,700 INFO sqlalchemy.engine.base.Engine ('2020-06-27', 8304, 1308, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,700 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,704 INFO sqlalchemy.engine.base.Engine ('2020-06-28', 8308, 1311, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,708 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,712 INFO sqlalchemy.engine.base.Engine ('2020-06-29', 8312, 1312, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,716 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,720 INFO sqlalchemy.engine.base.Engine ('2020-06-30', 8318, 1317, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,724 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,728 INFO sqlalchemy.engine.base.Engine ('2020-07-01', 8325, 1320, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,732 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,736 INFO sqlalchemy.engine.base.Engine ('2020-07-02', 8340, 1323, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,744 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,744 INFO sqlalchemy.engine.base.Engine ('2020-07-03', 8347, 1323, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,748 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,752 INFO sqlalchemy.engine.base.Engine ('2020-07-04', 8358, 1330, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,756 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,764 INFO sqlalchemy.engine.base.Engine ('2020-07-05', 8368, 1331, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,768 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,768 INFO sqlalchemy.engine.base.Engine ('2020-07-06', 8376, 1334, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,772 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,776 INFO sqlalchemy.engine.base.Engine ('2020-07-07', 8392, 1336, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,796 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,796 INFO sqlalchemy.engine.base.Engine ('2020-07-08', 8414, 1339, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,804 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,808 INFO sqlalchemy.engine.base.Engine ('2020-07-09', 8437, 1340, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,816 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,820 INFO sqlalchemy.engine.base.Engine ('2020-07-10', 8468, 1342, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,824 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,828 INFO sqlalchemy.engine.base.Engine ('2020-07-11', 8473, 1344, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,836 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,840 INFO sqlalchemy.engine.base.Engine ('2020-07-12', 8475, 1348, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,840 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,844 INFO sqlalchemy.engine.base.Engine ('2020-07-13', 8482, 1350, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,856 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,860 INFO sqlalchemy.engine.base.Engine ('2020-07-14', 8485, 1354, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,864 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,868 INFO sqlalchemy.engine.base.Engine ('2020-07-15', 8500, 1358, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,872 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,876 INFO sqlalchemy.engine.base.Engine ('2020-07-16', 8517, 1358, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,884 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,888 INFO sqlalchemy.engine.base.Engine ('2020-07-17', 8536, 1359, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,896 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,900 INFO sqlalchemy.engine.base.Engine ('2020-07-18', 8539, 1359, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,900 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,904 INFO sqlalchemy.engine.base.Engine ('2020-07-19', 8540, 1363, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,908 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,916 INFO sqlalchemy.engine.base.Engine ('2020-07-20', 8545, 1363, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,924 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,932 INFO sqlalchemy.engine.base.Engine ('2020-07-21', 8551, 1365, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,936 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,936 INFO sqlalchemy.engine.base.Engine ('2020-07-22', 8553, 1369, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,944 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,948 INFO sqlalchemy.engine.base.Engine ('2020-07-23', 8556, 1371, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,952 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,956 INFO sqlalchemy.engine.base.Engine ('2020-07-24', 8564, 1374, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,964 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)

2020-08-26 06:45:24,968 INFO sqlalchemy.engine.base.Engine ('2020-07-25', 8572, 1376, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,972 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,976 INFO sqlalchemy.engine.base.Engine ('2020-07-26', 8574, 1382, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,988 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,988 INFO sqlalchemy.engine.base.Engine ('2020-07-27', 8583, 1386, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:24,992 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:24,996 INFO sqlalchemy.engine.base.Engine ('2020-07-28', 8601, 1389, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:25,000 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:25,004 INFO sqlalchemy.engine.base.Engine ('2020-07-29', 8614, 1391, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:25,008 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:25,008 INFO sqlalchemy.engine.base.Engine ('2020-07-30', 8625, 1393, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:25,016 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:25,020 INFO sqlalchemy.engine.base.Engine ('2020-07-31', 8642, 1394, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:25,024 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:25,028 INFO sqlalchemy.engine.base.Engine ('2020-08-01', 8657, 1394, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:25,032 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:25,036 INFO sqlalchemy.engine.base.Engine ('2020-08-02', 8662, 1396, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:25,040 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:25,044 INFO sqlalchemy.engine.base.Engine ('2020-08-03', 8665, 1399, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:25,048 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:25,052 INFO sqlalchemy.engine.base.Engine ('2020-08-04', 8669, 1402, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:25,056 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:25,060 INFO sqlalchemy.engine.base.Engine ('2020-08-05', 8671, 1403, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:25,064 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:25,068 INFO sqlalchemy.engine.base.Engine ('2020-08-06', 8680, 1403, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:25,072 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:25,076 INFO sqlalchemy.engine.base.Engine ('2020-08-07', 8690, 1403, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:25,080 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:25,088 INFO sqlalchemy.engine.base.Engine ('2020-08-08', 8694, 1404, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:25,092 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:25,096 INFO sqlalchemy.engine.base.Engine ('2020-08-09', 8696, 1405, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:25,100 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:25,104 INFO sqlalchemy.engine.base.Engine ('2020-08-10', 8697, 1408, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:25,108 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:25,112 INFO sqlalchemy.engine.base.Engine ('2020-08-11', 8704, 1409, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:25,116 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:25,120 INFO sqlalchemy.engine.base.Engine ('2020-08-12', 8705, 1411, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:25,124 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:25,128 INFO sqlalchemy.engine.base.Engine ('2020-08-13', 8707, 1416, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:25,132 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:25,136 INFO sqlalchemy.engine.base.Engine ('2020-08-14', 8710, 1420, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:25,140 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:25,140 INFO sqlalchemy.engine.base.Engine ('2020-08-15', 8714, 1420, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:25,144 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:25,148 INFO sqlalchemy.engine.base.Engine ('2020-08-16', 8723, 1420, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:25,156 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:25,164 INFO sqlalchemy.engine.base.Engine ('2020-08-17', 8725, 1421, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:25,168 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:25,172 INFO sqlalchemy.engine.base.Engine ('2020-08-18', 8731, 1421, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:25,176 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:25,180 INFO sqlalchemy.engine.base.Engine ('2020-08-19', 8749, 1424, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:25,183 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:25,184 INFO sqlalchemy.engine.base.Engine ('2020-08-20', 8767, 1424, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:25,188 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:25,192 INFO sqlalchemy.engine.base.Engine ('2020-08-21', 8784, 1426, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:25,196 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:25,200 INFO sqlalchemy.engine.base.Engine ('2020-08-22', 8793, 1426, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:25,204 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:25,204 INFO sqlalchemy.engine.base.Engine ('2020-08-23', 8808, 1426, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:25,212 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:25,216 INFO sqlalchemy.engine.base.Engine ('2020-08-24', 8825, 1429, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:25,220 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:25,220 INFO sqlalchemy.engine.base.Engine ('2020-08-25', 8836, 1443, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:25,228 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-08-26 06:45:25,232 INFO sqlalchemy.engine.base.Engine ('2020-08-26', 8836, 1443, '2020-08-26 06:45:17.772911')
2020-08-26 06:45:25,264 INFO sqlalchemy.engine.base.Engine COMMIT